### ISSUE TITLE
Problem with webpage adaptation to iPad

### ISSUE THREAD

**Issue by ibarryyan** [xiaoli1999/custom-avatar#3] opened 2023-09-29 11:21 UTC
![微信图片_20230929191936](https://github.com/xiaoli1999/custom-avatar/assets/62547564/d5e53767-f5e7-4793-9719-4e3d8b3f1560)

**Comment by xiaoli1999** [comment] 2023-09-29 14:59
谢谢你发现并提出了这个问题，请告诉我你的iPad像素尺寸。 Thank you for discovering this issue，Please tell me the pixel size of your iPad。

**Comment by ibarryyan** [comment] 2023-10-04 02:57
@xiaoli1999 My iPad is iPad mini5 , size is 2048x1536

**Comment by xiaoli1999** [comment] 2023-10-07 01:50
@ibarryyan , Sorry, I don't have any related devices and can only use Chrome to simulate iPad Mini 5. However, this issue has not been reproduced. Below is a screenshot.

![微信图片_20231007094115](https://github.com/xiaoli1999/custom-avatar/assets/68105748/51bb552f-bc83-4a84-99f7-e3a73d02740a)
![1696642896836](https://github.com/xiaoli1999/custom-avatar/assets/68105748/b1d77ec1-978b-4dd1-b785-5edaa221f267)

I need you to provide more detailed information.
- Browser Information
- Device Information
- How to reproduce the problem
- Reproduction steps and screen recording
- And other factors or environments that may cause the problem

**Comment by Alivan-P** [comment] 2023-11-08 05:07
This problem only occurs on ios devices and cannot be reproduced on Android and browser simulation devices. My solution is to explicitly specify "position: relative" in the "App.vue" file when adapting the "main" style of the mobile terminal. It works fine on all devices.
```
/* 兼容移动端 */
@media only screen and (max-width: 768px) {
    ...

    main {
        ...
        //fix webkit kernel browser position problem #3
        position: relative;

        .avatar-warp {
```

**Comment by xiaoli1999** [comment] 2023-11-09 03:06
Thank you very much for your reply. It is precisely because of occasional occurrences on iOS devices that I am unable to locate the problem. I will try your solution to see if there are any other side effects, but I am still unable to confirm whether the issue with the iOS device has been resolved.

**Comment by xiaoli1999** [comment] 2023-11-09 03:06
> 该问题仅出现在ios设备上，在Android和浏览器模拟设备上无法重现。我的解决方案是在适配移动端的“main”样式时，在“App.vue”文件中显式指定“position:relative”。它在所有设备上都能正常工作。
> 
> ```
> /* 兼容移动端 */
> @media only screen and (max-width: 768px) {
>     ...
> 
>     main {
>         ...
>         //fix webkit kernel browser position problem #3
>         position: relative;
> 
>         .avatar-warp {
> ```

Thank you very much for your reply. It is precisely because of occasional occurrences on iOS devices that I am unable to locate the problem. I will try your solution to see if there are any other side effects, but I am still unable to confirm whether the issue with the iOS device has been resolved.

**Comment by xiaoli1999** [comment] 2023-11-13 06:23
@ibarryyan @Alivan-P 

I have created a new branch to fix the problem (**fix_ipad_position**), and the preview address is [ https://www.xiaoli.vip/custom-avatar-fix]( https://www.xiaoli.vip/custom-avatar-fix) ;

I would like to ask you to help me verify whether this issue has been resolved. I look forward to your reply. Thank you

**Comment by Alivan-P** [comment] 2023-11-15 02:19
@xiaoli1999 
I verified the results in Safari and IOS WeChat browsers, and it seems that the problem has been fixed.No side effects were discovered.

### **Safari：**
**new branch：**
![safari_new_branch](https://github.com/xiaoli1999/custom-avatar/assets/70468005/0cdca07b-f2d9-4422-9541-5c2a09d0888c)

**master branch：**
![safari_master_branch](https://github.com/xiaoli1999/custom-avatar/assets/70468005/334a03b9-7d57-407c-8fdc-897bca3da398)


### **WeChat：**
**new branch：**
![webchat_new_branch](https://github.com/xiaoli1999/custom-avatar/assets/70468005/6a3b4064-284a-4c3a-a23c-c1f5219d7b09)

**master branch：**
![wechat_master_branch](https://github.com/xiaoli1999/custom-avatar/assets/70468005/e623b0a9-6ad7-406c-baf1-91aee9c39d77)

**Comment by xiaoli1999** [comment] 2023-11-15 07:27
> @xiaoli1999 我在Safari和IOS微信浏览器中验证了结果，看来问题已经解决了，没有发现副作用。
> 
> ### **苹果浏览器：**
> **新分店：** ![safari_new_branch](https://user-images.githubusercontent.com/70468005/282982310-0cdca07b-f2d9-4422-9541-5c2a09d0888c.jpg)
> 
> **主分支：** ![safari_master_branch](https://user-images.githubusercontent.com/70468005/282982549-334a03b9-7d57-407c-8fdc-897bca3da398.jpg)
> 
> ### **微信：**
> **新分店：** ![webchat_new_branch](https://user-images.githubusercontent.com/70468005/282982760-6a3b4064-284a-4c3a-a23c-c1f5219d7b09.jpg)
> 
> **主分支：** ![wechat_master_branch](https://user-images.githubusercontent.com/70468005/282982791-e623b0a9-6ad7-406c-baf1-91aee9c39d77.jpg)



> @xiaoli1999 我在Safari和IOS微信浏览器中验证了结果，看来问题已经解决了，没有发现副作用。
> 
> ### **苹果浏览器：**
> **新分店：** ![safari_new_branch](https://user-images.githubusercontent.com/70468005/282982310-0cdca07b-f2d9-4422-9541-5c2a09d0888c.jpg)
> 
> **主分支：** ![safari_master_branch](https://user-images.githubusercontent.com/70468005/282982549-334a03b9-7d57-407c-8fdc-897bca3da398.jpg)
> 
> ### **微信：**
> **新分店：** ![webchat_new_branch](https://user-images.githubusercontent.com/70468005/282982760-6a3b4064-284a-4c3a-a23c-c1f5219d7b09.jpg)
> 
> **主分支：** ![wechat_master_branch](https://user-images.githubusercontent.com/70468005/282982791-e623b0a9-6ad7-406c-baf1-91aee9c39d77.jpg)

Thank you very much for your verification. I have merged this branch into the main branch and updated the website preview link. Thank you again for your contribution to this project

**Comment by xiaoli1999** [comment] 2023-11-15 07:27
> @xiaoli1999 我在Safari和IOS微信浏览器中验证了结果，显示问题已经解决了，没有发现效果。
> 
> ### **苹果浏览器：**
> **新分店：** ![safari_new_branch](https://user-images.githubusercontent.com/70468005/282982310-0cdca07b-f2d9-4422-9541-5c2a09d0888c.jpg)
> 
> **主要分支：** ![safari_master_branch](https://user-images.githubusercontent.com/70468005/282982549-334a03b9-7d57-407c-8fdc-897bca3da398.jpg)
> 
> ### **微信：**
> **新分店：** ![webchat_new_branch](https://user-images.githubusercontent.com/70468005/282982760-6a3b4064-284a-4c3a-a23c-c1f5219d7b09.jpg)
> 
> **主要分支：** ![wechat_master_branch](https://user-images.githubusercontent.com/70468005/282982791-e623b0a9-6ad7-406c-baf1-91aee9c39d77.jpg)

**Comment by xiaoli1999** [comment] 2023-11-15 07:27
@Alivan-P Thank you very much for your verification. I have merged this branch into the main branch and updated the website preview link. Thank you again for your contribution to this project

**Comment by xiaoli1999** [comment] 2023-11-15 07:31
[fix(App.vue): 修复ipad设备上头像框定位的bug](https://github.com/xiaoli1999/custom-avatar/pull/5)

**Closed by xiaoli1999** 2023-11-15 07:31 UTC
Labels: bug, question
